[project]
name = "sorrydb"
version = "0.1.0"
description = "Build a continously updating database of sorry statments in public Lean4 repositories"
authors = [{ name = "Your Name", email = "you@example.com" }]
license = { text = "Apache License" }
readme = "README.md"
requires-python = ">=3.13,<4.0"


[tool.poetry.dependencies]
gitpython = "*"
requests = "^2.32.3"
langchain = "^0.3.20"
langchain-anthropic = "^0.3.10"
dotenv = "^0.9.9"
langchain-openai = "^0.3.8"
langchain-google-genai = "^2.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[tool.poetry]
packages = [
	{ include = "sorrydb/scripts", from = "src" },
	{ include = "sorrydb/crawler", from = "src" },
	{ include = "sorrydb/repro", from = "src" },
	{ include = "sorrydb/database", from = "src" },
    { include = "sorrydb/llm_client", from = "src" }
]


[tool.poetry.scripts]
init_db = "sorrydb.scripts.init_db:main"
update_db = "sorrydb.scripts.update_db:main"
llm_proof = "sorrydb.scripts.llm_client:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
