name: CI

on:
  pull_request:
    paths:
      - 'sorrydb/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lean
        id: lean-action
        uses: leanprover/lean-action@v1
        with:
          auto-config: false
          # use the test Lean directory to tell `lean-action` whcih version of Lean to download
          lake-package-directory: "tests/mock_lean_repository"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          
      - name: Install dependencies
        run: poetry install --no-interaction
        
      - name: Run tests
        run: poetry run pytest

